config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"

  resources :users, only: [:new, :create]
  resources :posts, only: [:new, :create, :index, :show, :edit, :destroy]

  get "users/user_posts", to: "users#user_posts", as: "user_posts"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :user_id, :title, :body, presence: true

  validates :title, length: {minimum: 2}

  validates :body, length: {minimum: 10}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, format: {with: /[a-zA-Z0-9]+/, message: "can only be alphanumeric characters"}
  validates :name, length: {minimum: 2}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.all.order('created_at DESC')
  end
  
  def new
    @post = Post.new
    @user = current_user
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @posts = Post.all.order('created_at DESC')
    @user = current_user
  end

  def edit
    @post = Post.find(params[:id])
    @user = current_user
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      redirect_to posts_path, notice: "#{@post.title} deleted successfully"
    else
      flash.alert "Failed to delete #{@post.title}"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/turbo_controller.rb
class TurboController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def user_posts
    @posts = current_user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice">
      <%= notice %>
    </p>
    <p class="alert">
      <%= alert %>
    </p>

    <%= link_to image_tag("menu.svg"), root_path, id: "menu_button" %>

    <div id="header">
      <h1><%= link_to "Members Only!", posts_path %></h1>
    </div>

    <div id="sidebar">
      <%= yield :sidebar %>

      <li id="new_post_nav">
        <h3><%= link_to "New Post", new_post_path %></h3>
      </li>

      <% unless user_signed_in? %>
        <li id="sign_in_nav">
          <h3><%= link_to "Sign in", new_user_session_path %></h3>
        </li>

        <li id="sign_up_nav">
          <h3><%= link_to "Sign up", new_user_registration_path %></h3>
        </li>
      <% end %>

      <% if user_signed_in? %>
        <li id="my_posts_nav">
          <h3><%= link_to "My Posts", user_posts_path %></h3>
        </li>

        <li id="sign_out_nav">
          <h3><%= link_to "Sign out", destroy_user_session_path, data: {turbo_method: :delete} %></h3>
        </li>
      <% end %>
    </div>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_post_form.html.erb
<div class="form_container">
    <p class="name_message">
        Posting as <%= @user.name %>
    </p>
    
    <%= form_with model: @post, id: "post_form" do |form| %>
        <div id="form_title">
            <%= form.label :title %>
            <%= form.text_field :title %>
        </div>
    
        <div id="form_body">
            <%= form.label :body %>
            <%= form.text_area :body %>
        </div>
    
        <%= form.submit %>
    <% end %>
</div>

app/views/posts/_post_list.html.erb
<% @posts.each do |post| %>
    <%= link_to post_path(post), class: "posts" do %>
        <li class="post_title sidebar">
            <%= post.title %>
            <% if user_signed_in? %>
               by <%= post.user.name %>
            <% end %>
        </li>

        <li class="post_body sidebar">
            <%= post.body %>
        </li>
    <% end %>
<% end %>

app/views/posts/edit.html.erb
<%= render "post_form" %>

app/views/posts/index.html.erb
<div id="index_container">
    <%= render "post_list" %>
</div>

app/views/posts/new.html.erb
<p class="name_message">
    Posting as <%= @user.name %>
</p>

<%= form_with model: @post do |form| %>
    <div id="form_title">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div id="form_body">
        <%= form.label :body %>
        <%= form.text_area :body %>
    </div>

    <%= form.submit %>
<% end %>

app/views/posts/show.html.erb
<% content_for :sidebar do %>
    <ul id="sidebar_post_list">
        <%= render "post_list" %>
    </ul>
<% end %>

<div id="post_container">
    <h2 id="post_title">
        <%= @post.title %>
    </h2>
    
    <h3 id="post_author">
        <% if user_signed_in? %>
            <%= @post.user.name %>
        <% else %>
            Post author is only visible to logged in users!
        <% end %>
    </h3>
    
    <p id="post_body">
        <%= @post.body %>
    </p>
    
    <% if @post.user == @user %>
        <%= link_to image_tag("edit.svg"), edit_post_path, id: "edit_link" %>
        <%= link_to image_tag("delete.svg"), post_path, data: {turbo_method: :delete,  turbo_confirm: "Are you sure you want to delete this post?"}, id: "delete_link" %>
    <% end %>
</div>

app/views/users/user_posts.html.erb
<%= render "posts/post_list" %>